package server
import("encoding/json";"net/http";"strconv";"strings";"github.com/stockyard-dev/stockyard-mailbag/internal/store")
func(s *Server)handleListTemplates(w http.ResponseWriter,r *http.Request){list,_:=s.db.ListTemplates();if list==nil{list=[]store.Template{}};writeJSON(w,200,list)}
func(s *Server)handleCreateTemplate(w http.ResponseWriter,r *http.Request){var t store.Template;json.NewDecoder(r.Body).Decode(&t);if t.Name==""||t.Subject==""||t.Body==""{writeError(w,400,"name, subject, body required");return};if err:=s.db.CreateTemplate(&t);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,201,t)}
func(s *Server)handleDeleteTemplate(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.DeleteTemplate(id);writeJSON(w,200,map[string]string{"status":"deleted"})}
func(s *Server)handleListMessages(w http.ResponseWriter,r *http.Request){status:=r.URL.Query().Get("status");limit,_:=strconv.Atoi(r.URL.Query().Get("limit"));list,_:=s.db.ListMessages(status,limit);if list==nil{list=[]store.Message{}};writeJSON(w,200,list)}
func(s *Server)handleSendMessage(w http.ResponseWriter,r *http.Request){var req struct{TemplateID *int64 `json:"template_id"`;To string `json:"to"`;Subject string `json:"subject"`;Body string `json:"body"`;Vars map[string]string `json:"vars"`};json.NewDecoder(r.Body).Decode(&req);if req.To==""{writeError(w,400,"to required");return};m:=&store.Message{TemplateID:req.TemplateID,ToAddr:req.To,Subject:req.Subject,Body:req.Body};if req.TemplateID!=nil{t,err:=s.db.GetTemplate(*req.TemplateID);if err==nil{m.Subject=t.Subject;m.Body=t.Body;for k,v:=range req.Vars{m.Subject=strings.ReplaceAll(m.Subject,"{{"+k+"}}",v);m.Body=strings.ReplaceAll(m.Body,"{{"+k+"}}",v)}}};if m.Subject==""||m.Body==""{writeError(w,400,"subject and body required");return};if err:=s.db.SendMessage(m);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,201,m)}
func(s *Server)handleUpdateMessage(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);var req struct{Status string `json:"status"`;Error string `json:"error"`};json.NewDecoder(r.Body).Decode(&req);s.db.UpdateMessageStatus(id,req.Status,req.Error);writeJSON(w,200,map[string]string{"status":"updated"})}
func(s *Server)handleDeleteMessage(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.DeleteMessage(id);writeJSON(w,200,map[string]string{"status":"deleted"})}
func(s *Server)handleStats(w http.ResponseWriter,r *http.Request){m,_:=s.db.MessageStats();writeJSON(w,200,m)}
